### ISSUE TITLE
Make systems optional

### ISSUE THREAD

**Issue by kvark** [kvark/simplecs#2]
@mtsr

> I kind of feel it could even do without the systems, since that adds so little that isn't easy to do for the user, which would get rid of the $param and allow more complex stuff. Although the systems don't really get in the way either.

**Comment by mtsr** [comment]
More complex stuff like systems running in parallel, I mean.

**Comment by kvark** [comment]
Systems are not implemented for `secs` (#5), so this is partially addressed. Laziness FTW!

**Comment by kvark** [comment]
Technically, you can just ignore `System`s, pass in `()` to the macro parameter, and roll in your own things. I reviewed the way systems are set in `ecs` and came to conclusion that they are useful and non-intrusive.

If we ever get parallel processing systems, I'd be happy to replace the current ones with them.
Therefore, I'm closing this. Hope you don't mind ;)
